name: Deploy to Xserver

on:
  push:
    branches:
      - main # mainブランチにプッシュされた時に発火

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Xserver to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Xserver via rsync
        # 変更されたファイルだけを同期するrsyncコマンド
        # EC-CUBEの公開パスに合わせて展開先（DEST_DIR）を指定
        run: |
          rsync -avz --exclude '.git' --exclude '.github' --exclude 'var/' --exclude 'vendor/' --exclude 'node_modules/' -e "ssh -v -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=+ssh-rsa" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEST_DIR }}/
